default_language_version:
    python: python3.10
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: debug-statements
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.10.0
      hooks:
          - id: reorder-python-imports
            args: [--py310-plus]
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
            args: [--line-length=79]
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.4.1
      hooks:
          - id: mypy
            additional_dependencies: [types-all]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.9-for-vscode"
      hooks:
          - id: prettier
            args: [--tab-width=4, --no-semi]
            types_or: [ts, css]
    -   repo: https://github.com/pre-commit/mirrors-eslint
        rev: 'v8.43.0'
        hooks:
        -   id: eslint
            files: ts
            types: [file]
    - repo: local
      hooks:
        - id: tsc
          name: tsc
          entry: tsc -p client/
          language: node
          pass_filenames: false
          always_run: true
          additional_dependencies: [typescript]
